### ISSUE TITLE
run tools/analysis_tools/benchmark.py with mim

### ISSUE THREAD

**Issue by Patrickctyyx** [open-mmlab/mim#102]
how to run `tools/analysis_tools/benchmark.py` which is required for  distributed mode?

**Comment by kennymckormick** [comment]
Hi, Patrick. Currently, the mim command run does not support distributed mode. If you want to run the benchmark script, you can only set launcher as none.

**Comment by Patrickctyyx** [comment]
OK, thanks for your reply
