### ISSUE TITLE
auto install gpu verison when docker build

### ISSUE THREAD

**Issue by mofanke** [open-mmlab/mim#110]
**Describe the feature**

in my Dockerfile , i install mmcv-full cuda version first, by when i install other mmlab module , it would reinstall another verison mmcv-full by requirements , and could be a  cpu version.

i found mim will install gpu version when torch.cuda.is_available() 

so , is there a way , i can build a image install gpu verison and without gpu machines

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

CI/CD auto build docker images , maybe without gpu 

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

maybe make FORCE_CUDA  environment variable work 
and cuda verison can get from torch.version.cuda  or  other environment variable

**Comment by zhouzaida** [comment]
Hi @mofanke , sorry for the late reply. Now supports installing gpu version without gpu machine. More details at https://github.com/open-mmlab/mim/pull/96.
