### ISSUE TITLE
Bypass SSL check when installing packages

### ISSUE THREAD

**Issue by Xylobyte** [open-mmlab/mim#115]
I'm working in an environment with a strict custom proxy enforcement which blocks ssl verification to many sites including package hosts. Is there a way to bypass this verification similar to how pip allows the following?
```
--trusted-host {host}
```

**Comment by ApoorvaSuresh** [comment]
Hi, same issue here. Did you find a solution? If so, could you please share it?

**Comment by Xylobyte** [comment]
> Hi, same issue here. Did you find a solution? If so, could you please share it?

Unfortunately I have not yet found a solution

**Comment by tik0** [comment]
Can you try to add a `verify=False` to the request call in https://github.com/open-mmlab/mim/blob/main/mim/utils/utils.py#L144

**Comment by Xylobyte** [comment]
This doesn't seem to make a difference. It still attempts to verify SSL when collecting packages

**Comment by zhouzaida** [comment]
Hi @Xylobyte , thanks for your feedback and sorry for my late reply. We are refactoring the logic to install packages and then this case can be handled.

**Comment by zhouzaida** [comment]
Hi @Xylobyte, we have released v0.2.0. You could upgrade your openmim by `pip install -U openmim` and then you can pass `--trusted-host` option to `mim install`.
