### ISSUE TITLE
install mmcv-full failed

### ISSUE THREAD

**Issue by xiexinch** [open-mmlab/mim#12]
system: `ubuntu 18.04`
cuda: `cuda 10.2`
python version: `python 3.7`
pytorch version: `torch 1.8.1`
command: `mim install mmcv-full`

![WXWorkCapture_16215783608763](https://user-images.githubusercontent.com/15952744/119092288-d3dbc200-ba40-11eb-8ff8-79d6fa47e799.png)

**Comment by RangiLyu** [comment]
I met the same problem. Run
```
export MKL_THREADING_LAYER=GNU
```
works on me. You can try this method.

**Comment by zhouzaida** [comment]
refer to https://github.com/pytorch/pytorch/issues/37377
