### ISSUE TITLE
Error when "mim install mmdet" on Windows10

### ISSUE THREAD

**Issue by Robotatron** [open-mmlab/mim#151]
On Windows 10, run "mim install mmdet":
```
ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
```

**Comment by ice-tong** [comment]
Hi @Robotatron , there are a same issues in https://github.com/open-mmlab/mmdetection/issues/7348. I hope you find this information helpful. ^_^

**Comment by Robotatron** [comment]
> Hi @Robotatron , there are a same issues in [open-mmlab/mmdetection#7348](https://github.com/open-mmlab/mmdetection/issues/7348). I hope you find this information helpful. ^_^

`conda install -c esri pycocotools` fixed the issue for me!
