### ISSUE TITLE
Cityscapes, LVIS v0.5 and v1 models are not properly registered in `mim`

### ISSUE THREAD

**Issue by duguyue100** [open-mmlab/mim#162]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://openmim.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

Thanks for providing a rich set of zoo models through `mim`'s download function.

1. `cityscapes` models are not in the registered models.
2. `lvis_v0.5` models are not in the registered models.
3. Some `lvis_v1 ` models cannot be loaded properly. Some of them are not in the registered models.

**Reproduction**

The following model ids are not in the registered models or cannot be loaded via `mim`'s download.

```
Not available:
        "mask_rcnn_r50_fpn_1x_cityscapes"
        "mask_rcnn_r50_fpn_sample1e-3_mstrain_2x_lvis_v0.5"
        "mask_rcnn_r101_fpn_sample1e-3_mstrain_2x_lvis_v0.5"
        "mask_rcnn_x101_32x4d_fpn_sample1e-3_mstrain_2x_lvis_v0.5"
        "mask_rcnn_x101_64x4d_fpn_sample1e-3_mstrain_2x_lvis_v0.5"
        "mask_rcnn_r50_fpn_sample1e-3_mstrain_1x_lvis_v1"
        "mask_rcnn_r101_fpn_sample1e-3_mstrain_1x_lvis_v1"
        "mask_rcnn_x101_32x4d_fpn_sample1e-3_mstrain_1x_lvis_v1"
        "mask_rcnn_x101_64x4d_fpn_sample1e-3_mstrain_1x_lvis_v1"
Not loadable:
        "mask_rcnn_r50_fpn_random_seesaw_loss_mstrain_2x_lvis_v1"
        "mask_rcnn_r50_fpn_random_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
        "mask_rcnn_r101_fpn_random_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
        "mask_rcnn_r50_fpn_sample1e-3_seesaw_loss_mstrain_2x_lvis_v1"
        "mask_rcnn_r50_fpn_sample1e-3_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
        "mask_rcnn_r101_fpn_sample1e-3_seesaw_loss_mstrain_2x_lvis_v1"
        "mask_rcnn_r101_fpn_sample1e-3_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
        "cascade_mask_rcnn_r101_fpn_random_seesaw_loss_mstrain_2x_lvis_v1"
        "cascade_mask_rcnn_r101_fpn_random_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
        "cascade_mask_rcnn_r101_fpn_sample1e-3_seesaw_loss_mstrain_2x_lvis_v1"
        "cascade_mask_rcnn_r101_fpn_sample1e-3_seesaw_loss_normed_mask_mstrain_2x_lvis_v1"
```

1. Did you make any modifications on the code or config? Did you understand what you have modified?

no

2. What dataset did you use?

`cityscapes`, `lvis_0.5`, `lvis_v1`

**Environment**

Python3.8 from conda + Ubuntu 22.04

**Error traceback**
If applicable, paste the error trackback here.

When the model can't be loaded, this value error appeared:

```none
File ~/miniconda3/lib/python3.8/site-packages/mim/commands/download.py:129, in download(package, configs, dest_root)
    127                 break
    128         else:
--> 129             raise ValueError(
    130                 highlighted_error(f'{config_path} is not found.'))
    132 return checkpoints

ValueError: /home/yuhuang/miniconda3/lib/python3.8/site-packages/mmdet/seesaw_loss/mask_rcnn_r50_fpn_random_seesaw_loss_mstrain_2x_lvis_v1.py is not found.
```

**Comment by ice-tong** [comment]
Hi @duguyue100, thanks for the feedback!

This is a known issue caused by the missing `metafile.yml` or invalid `metafile.yml` in mmdet.

We will push to fix this later. ^_^
