### ISSUE TITLE
Installation of rc versions does not work correctly

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mim#169]
**Description**
If I run this in the command line:
`pip install openmim`
`mim install mmdet>=3.0.0rc0`
`mim list`
prints
```
Package    Version    Source
---------  ---------  -----------------------------------------
mmdet      2.25.3     https://github.com/open-mmlab/mmdetection
```

**Expected behaviour**
`mim install mmdet>=3.0.0rc0` should install `mmdet v3.0.0rc2` (the latest rc at the time of writing).

**Probable cause**
Maybe `mim` installs the newest package newer than `3.0.0rc0` by date. This can lead to the above behaviour.

Perhaps the version numbers need to be parsed instead of just installing by date of release?

**Comment by ice-tong** [comment]
Hi @vavanade,you should try `mim install 'mmdet>=3.0.0rc0'`. ^_^

**Comment by vavanade** [comment]
It does not work with quotes on Windows CMD. There seems to be some sort of escaping issue. This is the error message:
```
ERROR: Invalid requirement: "'mmdet"
```

**Comment by ice-tong** [comment]
Hi @vavanade, for Windows CMD, you should use a double quotes:

```
mim install "mmdet>=3.0.0rc0"
```

**Comment by vavanade** [comment]
@ice-tong You are right, it works. I thought I tried double quotes but it didn't work. It works just fine.

I am sorry to waste your time. You can close this.

**Comment by ice-tong** [comment]
@vavanade You are welcome. ^_^

I will close this issue as completed, feel free to feedback if you have any other problems.
