### ISSUE TITLE
error with mmyolo

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mim#170]
Please help me, trying to test download mmyolo config via python:

env:

```bash
openmim==0.3.2
mmyolo=0.1.1
mmengine==0.1.0
mmcv==2.0.0rc2
mmdet==3.0.0rc2
```

command:

```python
from mim import download

filepath = download("mmyolo", ["yolov5_n-v61_syncbn_fast_8xb16-300e_coco"], dest_root=".")
```

error:

```bash
[.../lib/python3.8/site-packages/mmyolo/model-index.yml or .../lib/python3.8/site-packages/mmyolo/model_zoo.yml is not found, please upgrade your mmyolo to support search command
```

**Comment by ice-tong** [comment]
Hi @fcakyon , it seems the mmyolo has not add the `.mim` extension successfully during setup.

I will fix this as soon as possible.

**Comment by ice-tong** [comment]
Hi @fcakyon, I just found this issue has been fixed by https://github.com/open-mmlab/mmyolo/pull/205.

You can try to the checkout dev branch of mmyolo, and install mmyolo in editable mode.

```bash
git clone https://github.com/ice-tong/mmyolo.git
git checkout dev
mim install -v -e .
```

**Comment by ice-tong** [comment]
@fcakyon I will close this issue, feel free to reopen it if you have any problems. ^_^
