### ISSUE TITLE
How to install and use mim?

### ISSUE THREAD

**Issue by cnmarinas** [open-mmlab/mim#187]
Hi there,
I have tried to install openmim by:
`pip install openmim`

but when I tried to install mmcv-full, it says Command 'mim' not found

`mim install mmcv-full`

What have I done wrong? Many thanks!

**Comment by cnmarinas** [comment]
Found the issue: installed packages not in the path.

**Comment by Runzhi354** [comment]
> 
How to solve this problem?

**Comment by zimenglan-sysu-512** [comment]
hi @cnmarinas 
how did u solve the problem? need help! 
thanks.

**Comment by xy-lin** [comment]
cannot remember exactly, something to do with installed path of the mim. Try to find out where the mim is installed, then make sure that path is searchable.
