### ISSUE TITLE
这个mim包管理工具，是否支持像pip那样的download-only命令？

### ISSUE THREAD

**Issue by dongfangduoshou123** [open-mmlab/mim#188]
您好，我想问下，这个mim包管理工具，是否支持像pip那样的download-only名命，将要安装的包，通过mim命令下载下来（包括把依赖也下载下来），而不是安装；用途就是通过这种仅下载的命令，把安装包下载下来后，往内网环境的生产环境部署的需求；应该很多工业界的安装需求，都是这样的gpu在内网环境上，不能访问公网。

**Comment by ice-tong** [comment]
@dongfangduoshou123 你好，目前 MIM 未提供对应 pip download 的功能。 

mim install 只是在 pip install 基础上增加了以下两个额外的操作：
1. 自动添加 mmcv-full 当前环境所需预编译包的 findliink
2. 处理 OpenMMLab 算法库之间的依赖（requirements/mminstall.txt）

通常情况下，你应该可以通过 `pip download mmcv-full -f xxxx ` 达到相同的目的。
