### ISSUE TITLE
Can we submit the mim command asynchronously？

### ISSUE THREAD

**Issue by GhaSiKey** [open-mmlab/mim#190]
Could mim support asynchronous commits ”--async“ - or, alternatively, log output redirection “--output”  to redirect the generated logs to another file?
mim是否可以支持异步提交--async，或者换种方式，支持日志输出重定向--output，把生成的日志重定向之别的文件。

**Comment by ice-tong** [comment]
We can use `--srun-args` for passing extra srun arguments~
