### ISSUE TITLE
Make openmim available on conda-forge

### ISSUE THREAD

**Issue by giswqs** [open-mmlab/mim#193]
**Describe the feature**

**Motivation**
It would be great to publish openmim available on conda-forge. Otherwise, downstream packages of openmim can't be made available on conda-forge. Making it available on conda-forge will benefit all downstream packages and numerous conda-forge users. 

**Related resources**
An example of conda-forge recipe: https://github.com/conda-forge/staged-recipes/pull/21714

**Additional context**
Relevant issue: https://github.com/autogluon/autogluon/issues/612

**Comment by arturdaraujo** [comment]
I fully agree! If any help is needed I'm here. Just a reminder that you only need to publish once, because the updates are automatically done. It's worth entering the conda-forge ecosystem.
@OpenMMLab

**Comment by zhouzaida** [comment]
Hi @giswqs and @arturdaraujo, thanks for your suggestion. It sounds good and we will make openmim available ASAP.

**Comment by arturdaraujo** [comment]
We don't mind publishing and we can add you as maintainer. @giswqs is an experienced conda-forge publisher

**Comment by giswqs** [comment]
I just checked. openmin requires `model-index`, so will need to make `model-index` available first. 

![image](https://user-images.githubusercontent.com/5016453/212231064-d5716d39-22f2-456b-b536-6a02fc5c2e4c.png)

**Comment by giswqs** [comment]
@zhouzaida is `model-index` an absolute requirement for `openmim`? Can it be made as an optional package?

**Comment by arturdaraujo** [comment]
I think this is the one https://pypi.org/project/model-index/
I can't see on github though

**Comment by zhouzaida** [comment]
> @zhouzaida is `model-index` an absolute requirement for `openmim`? Can it be made as an optional package?

Runtime requirements can be found at https://github.com/open-mmlab/mim/blob/main/requirements/install.txt

**Comment by arturdaraujo** [comment]
Let's publish model-index

**Comment by giswqs** [comment]
And `model-index` requires `modelindex`, so we need `modelindex` as well. https://pypi.org/project/modelindex/

![image](https://user-images.githubusercontent.com/5016453/212231719-64429395-b853-464f-9926-89d799a24a66.png)

**Comment by zhouzaida** [comment]
`modelindex` is an alias for the [model-index](https://pypi.org/project/model-index/) library.

**Comment by arturdaraujo** [comment]
What a rabbit hole
Let's do it

**Comment by giswqs** [comment]
It is indeed a rabbit hole. And `modelindex` recipe fails to create. We might be stuck. 

![image](https://user-images.githubusercontent.com/5016453/212231983-9cac17e8-93da-45cf-838a-348296062bd1.png)

**Comment by arturdaraujo** [comment]
modelindex has no github page it seems

**Comment by arturdaraujo** [comment]
What a useless thing is "alias package". Does it make sense to simply remove modelindex from the recipe? I think we can talk to the devs from conda-forge

**Comment by arturdaraujo** [comment]
Another alternative would be to ask model-index maintainers to remove modelindex, but they don't see to be active for a while

**Comment by giswqs** [comment]
I agree with you. What a weird way to list an alias package of itself as a dependency, but that alias package is not being maintained.

**Comment by giswqs** [comment]
It seems model-index is not heavily used by openmin. The `load()` function is used once, and `ModelIndex` is used twice. I am not sure if it makes sense to make `model-index`  an optional package for openmin since `model-index` is not actively maintained. Basically, put the `modelindex` import statement within the function rather than at the top-level import. In that way, it does not need to be listed as a dependency for PyPI. This can be a backup plan in case we can't get `modelindex` on conda-forge. 

@zhouzaida Is it something you would consider?

https://github.com/open-mmlab/mim/blob/main/mim/commands/search.py#L295
```python
from modelindex.load_model_index import load
from modelindex.models.ModelIndex import ModelIndex
```

**Comment by arturdaraujo** [comment]
The matrix-index package seems to have one more active maintainer, I think we can wait a couple of days for @datumbox though

**Comment by arturdaraujo** [comment]
This looks good!

**Comment by zhouzaida** [comment]
> It seems model-index is not heavily used by openmin. The `load()` function is used once, and `ModelIndex` is used twice. I am not sure if it makes sense to make `model-index` an optional package for openmin since `model-index` is not actively maintained. Basically, put the `modelindex` import statement within the function rather than at the top-level import. In that way, it does not need to be listed as a dependency for PyPI. This can be a backup plan in case we can't get `modelindex` on conda-forge.
> 
> @zhouzaida Is it something you would consider?
> 
> https://github.com/open-mmlab/mim/blob/main/mim/commands/search.py#L295
> 
> ```python
> from modelindex.load_model_index import load
> from modelindex.models.ModelIndex import ModelIndex
> ```

This command `mim search` is used frequently and it would be user-friendly to install `model-index` automatically when installing `openmim`.

**Comment by giswqs** [comment]
@zhouzaida Understood. Let's get `model-index` published first.

**Comment by arturdaraujo** [comment]
@zhouzaida

**Comment by giswqs** [comment]
`openmim` and `model-index` have been published on conda-forge. 
https://anaconda.org/conda-forge/openmim

@zhouzaida Would you be willing to be listed as a maintainer of the package on conda-forge? 
https://github.com/conda-forge/openmim-feedstock

**Comment by zhouzaida** [comment]
> `openmim` and `model-index` have been published on conda-forge. https://anaconda.org/conda-forge/openmim
> 
> @zhouzaida Would you be willing to be listed as a maintainer of the package on conda-forge? https://github.com/conda-forge/openmim-feedstock

Yes, I would. Thanks for your contributions.
