### ISSUE TITLE
subprocess.CalledProcessError: ...  returned non-zero exit status 1

### ISSUE THREAD

**Issue by wyhhyw123** [open-mmlab/mim#23]
when i run "mim run mmcls get_flops resnet101_b16x8_cifar10.py"  OR "mim run mmcls publish_model", it report the error 
 "subprocess.CalledProcessError: ...  returned non-zero exit status 1 ". How to solve this?

**Comment by kennymckormick** [comment]
To run `mim run mmcls get_flops resnet101_b16x8_cifar10.py`, `resnet101_b16x8_cifar10.py` needs to be a valid config under your current directory. If not, you need to use the absolute path for the config.

**Comment by wyhhyw123** [comment]
Another question, how to assign the path of dataset, each time i run 'mim mmcls resnet101_b16x8_cifar10.py', it will download dataset automaticlly

**Comment by zhouzaida** [comment]
@kennymckormick

**Comment by kennymckormick** [comment]
According to the config file: https://github.com/open-mmlab/mmclassification/blob/master/configs/_base_/datasets/cifar10_bs16.py. The dataset is saved at `data/cifar10`, which is a relative path. Thus you'd better run training commands in the same directory across time, or link the dataset before you run the command to avoid redundant downloads.
