### ISSUE TITLE
Build Wheel only use one cpu core

### ISSUE THREAD

**Issue by jnchen** [open-mmlab/mim#231]
**Describe the feature**
enable multi core build to accelerate package installation.

**Motivation**
i noticed that build package from mim when install it only use one cpu core, such as `mim install mmcv-full`. On my server i have 96 cpu core...., but i have to wait for a loooooooong time

**Comment by zhouzaida** [comment]
Hi @jnchen , you can install `psutil` to use more CPU cores to build mmcv. https://github.com/open-mmlab/mmcv/blob/df2dadb78db269c3d3463d56cf37fb966ad730b6/setup.py#L186
