### ISSUE TITLE
Notes of supporting installation by mim in downstream repositories

### ISSUE THREAD

**Issue by ly015** [open-mmlab/mim#35]
A few notes of supporting installation by mim in downstream repositories.

### Add extra files (e.g. tools/, configs/, model_zoo.yml) into the package path
1. Use the environment variable `MIM_SYMLINK_FILES=1` to indicate a package is being installed via mim.
2. Add symlinks to add extra files when installed by pip or from the source code.
3. Copy these files when installed by mim (because the cloned repo will be deleted after installation)

### Extra file path (TBD)
- [ ] Option 1: in the package folder with hidden filenames, e.g., `mmpose/.tools`
- [ ] Option 2: in a hidden folder in the package folder, e.g., `mmpose/.mim/tools`

**Comment by ZwwWayne** [comment]
I tend to option2 because it can also contain other files in the future.

**Comment by zhouzaida** [comment]
resolved by #68

**Comment by zhouzaida** [comment]
Thanks for your contribution
