### ISSUE TITLE
Allow to install CUDA version of MMCV-full through commands.

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mim#56]
**Describe the feature**
Allow to install CUDA version of MMCV-full through commands. For example, when typing `MMCV_WITH_OPS=1 mim install mmcv-full`, it should install a CUDA version MMCV-full no matter whether GPU is detected on the current machine. The correct CUDA version should be inferred by nvcc.

**Motivation**
Sometimes the training program runs on a computation cluster but the installation is done in a management cluster which does not have GPU but have nvcc.

**Comment by SebastienLinker** [comment]
I tried to use `mim install mmcv-full` within a `docker build`, but because of this CUDA stuffs won't compile. I found a solution by using `pip install mmcv-full` instead

**Comment by zhouzaida** [comment]
resolved by #96
