### ISSUE TITLE
mim install a package from github branch

### ISSUE THREAD

**Issue by chuong98** [open-mmlab/mim#60]
Hello, I want to use a different version of `mmdet` from a github branch. For example, from `jshilong/mmdetection`, brach `onnx_cascade`. I try 
```bash
    mim install mmdet -f https://github.com/jshilong/mmdetection.git@onnx_cascade
```
but it does not work yet. Thank you.

**Comment by zhouzaida** [comment]
thanks for your feedback. I am fixing the bug

**Comment by zhouzaida** [comment]
Resolved. We can use command `mim install git+https://github.com/jshilong/mmdetection.git@onnx_cascade` to install a package from GitHub branch.
