### ISSUE TITLE
mim(version 0.1.2)  install mmocr failed 

### ISSUE THREAD

**Issue by mofanke** [open-mmlab/mim#63]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://openmim.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
mim(version 0.1.2)  install mmocr failed 
`Traceback (most recent call last):
  File "/data/venv/mmlab/lib/python3.8/site-packages/mim/utils/utils.py", line 390, in call_command
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/open-mmlab/mmocr.git', '-b', 'v0.2.1', '/tmp/tmpu7gj5bj_/mmocr']' returned non-zero exit status 128.`
**Reproduction**

1. What command or script did you run?
mim install mmocr
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

there's no  v0.2.1 in  https://github.com/open-mmlab/mmocr.git

**Comment by zhouzaida** [comment]
hi @mofanke , thanks for your feedback. You can get the mmocr v0.2.1 in the https://github.com/open-mmlab/mmocr.git now
