### ISSUE TITLE
'mmseg' is not installed.

### ISSUE THREAD

**Issue by sijin-dm** [open-mmlab/mim#80]
Hi, when I try `mim list`, the following message is showed:
```
Package         Version    Source
--------------  ---------  ----------------------------------------------
mmcls           0.14.0     https://github.com/open-mmlab/mmclassification
mmcv            1.3.10     https://github.com/open-mmlab/mmcv
mmcv-full       1.3.9      https://github.com/open-mmlab/mmcv
mmsegmentation  0.16.0     http://github.com/open-mmlab/mmsegmentation
```
We can see that mmsegmentation is installed. When I use `mim train mmseg xxx.config`,  `mim` will remind me to install `mmseg` as `The codebase mmseg is not installed, do you want to install the latest release? `. However, there is a 'mmseg' package in https://pypi.org/project/mmseg/, which is not mmsegmentation actually. So errors occured as someone describe here: https://github.com/open-mmlab/mim/issues/55. 
BTW, I notice that even though `PKG2MODULE` and `MODULE2PKG` are setting in `mim/mim/utils/default.py`, there still are logical bugs somewhere.

**Comment by zhouzaida** [comment]
Sorry for the late reply. In fact, you should use `mim train mmsegmentation xxx.config`.

**Comment by Kinpzz** [comment]
@zhouzaida I had the same problem. The mim-example also use `mim train mmseg xxx.config` https://github.com/open-mmlab/mim-example/tree/master/nuimages_seg. When I use `mim train mmsegmentation xxx.config`, it shows `ValueError: Can't determine a unique package given abbreviation mmsegmentation`.

**Comment by zhouzaida** [comment]
> @zhouzaida I had the same problem. The [mim-example](https://github.com/open-mmlab/mim-example/tree/master/nuimages_seg) also uses `mim train mmseg xxx.config`. When I use `mim train mmsegmentation xxx.config`, it shows `ValueError: Can't determine a unique package given abbreviation mmsegmentation`.

hi @Kinpzz , thanks for your feedback. We are resolving the bug and you can degrade your mim version to temporarily solve the problem
