### ISSUE TITLE
Specifying gpu-ids with mim train

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mim#97]
**Describe the feature**
I would like to specify the gpu-ids when I run mim train.
 
 ```
 mim train mmcls config.py --gpu-ids 1
 ```
 
 Currently, I think I can only specify the gpus as shown below.

 ```
 mim train mmcls config.py --gpus 1
 ```

**Motivation**
It is inconvenient when to specify the gpu-ids.

**Related resources**
https://github.com/open-mmlab/mmclassification/blob/master/tools/train.py#L38-L43

**Comment by zhouzaida** [comment]
Hi @okotaku , the command `mim train mmcls config.py --gpu-ids 1 --gpus 1` should work well because `gpu-ids` will be parsed as `other_args` and they will also be passed to train.py.

https://github.com/open-mmlab/mim/blob/08a99cff036887883e59ae1a2dc21038219ceb41/mim/commands/train.py#L150-L151

**Comment by okotaku** [comment]
Thank you!

**Comment by okotaku** [comment]
When I try to use `mim train mmcls config.py --gpu-ids 1 --gpus 1` , I get the following error.

```
usage: train.py [-h] [--work-dir WORK_DIR] [--load-from LOAD_FROM] [--resume-from RESUME_FROM] [--no-validate] [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]] [--seed SEED]
                [--deterministic] [--options OPTIONS [OPTIONS ...]] [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]] [--launcher {none,pytorch,slurm,mpi}] [--local_rank LOCAL_RANK]
                config
train.py: error: argument --gpu-ids: not allowed with argument --gpus
```

**Comment by zhouzaida** [comment]
Please @kennymckormick have a look.

**Comment by kennymckormick** [comment]
Hi, okotaku. In mmcls, `--gpu-ids` and `--gpus` are two exclusive args. Maybe you can use `CUDA_VISIBLE_DEVICES=1 mim train mmcls config.py --gpus 1` instead.

**Comment by okotaku** [comment]
Thank you!
